[target.xtensa-esp32-none-elf]
runner = "espflash flash --baud 460800 --monitor --chip esp32"
# runner = "espflash flash --baud 115200 --monitor --chip esp32"

[env]
ESP_LOG = "debug"

WIFI_CHANNEL = "11"
WIFI_PASSWORD = "rusty-robot"   # CHANGE ME!!!
MESH_SSID = "RUSTY-ROBOT-MESH"

# two-character country info as described in the document ISO/IEC3166-1.
ESP_WIFI_CONFIG_COUNTRY_CODE = "US"
# disable USB debug for optimal performance
ESP_WIFI_CONFIG_PHY_ENABLE_USB = "false"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
