[package]
name = "rusty-robot-common"
version = "0.1.0"
license = "Apache-2.0"
edition = "2024"

[dependencies]
# log = { workspace = true }
static_cell = "*"
arrayvec = { version = "*", default-features = false }
